### ISSUE TITLE
MILESTONE: August 2020

### ISSUE THREAD

**Issue by ElderJames** [ant-design-blazor/ant-design-blazor#254]
Here are the milestones we plan to accomplish by August, and then release 0.3 :

# Components

- [x] Refactor and performance improvement
- [x] Localization for compontents
- [x] Add unit tests @dmoonfire 
- [x] Complete the form component @mutouzdl 
- [x] Use `TaskCompletionSource` to implement **promise-event** @zxyao145 
~~- [ ] [upload] supprot drag/drop @adsioj~~
~~- [ ] More features for table~~
~~- [ ] Filters~~
~~- [ ] Collapsible rows~~
- [x] Refactor select component
~~- [ ] Add tree-select~~
- [x] Fix known issues

# Ant Design Pro Blazor

https://github.com/ant-design-blazor/ant-design-pro-blazor

~~- [ ] Implement the pages in Ant Design Pro~~
- [x] Make it as `dotnet new` template
~~- [ ] Social authorization~~

# Docs

- [x] Icon List @1002527441 
- [x] Charts demo @TimChen44 @ElderJames 
~~- [ ] Dark mode~~
~~- [ ] Clean up the API list~~
