### ISSUE TITLE
MILESTONE: July 2020

### ISSUE THREAD

**Issue by ElderJames** [ant-design-blazor/ant-design-blazor#255]
Here are the milestones we plan to accomplish by July and then release 0.2 :

# Components

- [x] Rich Text Editor base on ~~[UEditor](https://github.com/notadd/neditor)~~ Vditor #242 
- [x] Add Chart Components base on [ant-design-charts](https://charts.ant.design/) #239 
    see [ant-design-charts-blazor](https://github.com/ant-design-blazor/ant-design-charts-blazor) repo for more detail.
- [ ] Complete the remaining components #3
  - [x] montions
~~- [ ] tree select~~
~~- [ ] form controls~~
  - [x] table sortable
~~- [ ] upload gallery~~

~~# Template~~

~~https://github.com/ant-design-blazor/Template~~

~~- [ ] Add login page and integrate Jwt login~~
~~- [ ] Create pro-layout Library~~

# Ant Design Pro

see [ant-design-pro-blazor](https://github.com/ant-design-blazor/ant-design-pro-blazor) repo for more detail.
