### ISSUE TITLE
MILESTONE: MID 2020

### ISSUE THREAD

**Issue by ElderJames** [ant-design-blazor/ant-design-blazor#3]
MILESTONE: MID 2020

# Components

The following are all of the components currently in ant-design. Let's Implement them together.

- [x] affix @Brian-Ding #98 
- [x] alert (#26) @ElderJames 
- [x] anchor @Brian-Ding #280 
- [x] auto-complete @iliuhai #251 
- [x] avatar @ElderJames 
- [x] back-top @GarvinTan  #53 
- [x] badge @ElderJames #160 
- [x] breadcrumb @ElderJames 
- [x] button @ElderJames 
- [x] calendar @mutouzdl #176 
- [x] card	@ElderJames 
- [x] carousel  @Brian-Ding #96
- [x] cascader @iliuhai #172 
- [x] checkbox @ElderJames @Zhuangkh #69
- [x] collapse @TimChen44  #226 
- [x] comment @Zhuangkh #80 
~~- [ ] config-provider~~
- [x] date-picker @mutouzdl #85 
- [x] descriptions @TimChen44 #224 
- [x] divider @ElderJames 
- [x] drawer @ElderJames @1002527441 @zxyao145 
- [x] dropdown @mutouzdl #93 
- [x] empty @mutouzdl #78 
- [x] form @mutouzdl @ElderJames @TimChen44   #168 
- [x] grid @ElderJames 
- [x] icon @ElderJames 
- [x] input-number @Brian-Ding @TimChen44  #45 
- [x] input (#33 ) @Brian-Ding @TimChen44  #33 
- [x] layout @ElderJames 
- [x] list @Setli (basic #91)
~~- [ ] mentions @1002527441~~
- [x] menu @ElderJames @mutouzdl #126 
- [x] message @zxyao145 #128 
- [x] modal @zxyao145 #167 
- [x] notification @zxyao145  #99 
- [x] page-header @TimChen44 #211 
- [x] pagination @ElderJames #130 
- [x] popconfirm @Zhuangkh #288 
- [x] popover @Zhuangkh #263 
- [x] progress @Brian-Ding #129 
- [x] radio @ElderJames #36 
- [x] rate @hrx521 #166 
- [x] result @ElderJames #113 
- [x] select  @thinkershare @iliuhai #196 
- [x] skeleton @TimChen44 #234 
- [x] slider @Brian-Ding #87 
- [x] space @ElderJames #115 
- [x] spin @ElderJames  #114 
- [x] statistic @hrx521 #205 
- [x] steps @rabbitism #46 
- [x] switch @ElderJames
- [x] table @AlseinX @ElderJames #75 
- [x] tabs @Brian-Ding #67 
- [x] tag @ElderJames  @1002527441
- [x] time-picker @mutouzdl #85 
- [x] timeline @ElderJames 
- [x] tooltip @Zhuangkh #131 
- [x] transfer @MountainTang #148 
~~- [ ] tree-select~~
- [x] tree @BlazorPlus #112 
- [x] typography @rabbitism #7 
- [x] upload @adsioj #276 

# Docs

~~- [ ] Support for Dark mode #31~~
- [x] Dynamic rendering of demo and markdown  #18 
- [x] Localization for English and Chinese #59 
- [x] Official-like theme
- [x] Cover offical demos as much as possible (check list: #141 )  @1002527441

# Build
- [x] Refactor the CI/CD in Github Actions #151 
- [x] Gitee Sync & Reload the Pages (f9066a81ae6ef6429ad1b15e14ed82b73e59f7cd)
- [x] PR Preview Pages (#48)

**Comment by turenc** [comment]
> You are awesome!

**Comment by ElderJames** [comment]
@turenc Welcome to join us 😄

**Comment by wuyang26** [comment]
are there some large data manage controls? for example:DataGrid /PivotGrid
and some data visualization controls,for example: chart/gauges/heatmap ?
and htmlDocumentEditor...

**Comment by ElderJames** [comment]
@wuyang26 Not yet in this milestone.
