### ISSUE TITLE
MILESTONE:  December 2020

### ISSUE THREAD

**Issue by ElderJames** [ant-design-blazor/ant-design-blazor#593]
Here are the milestones we plan to accomplish by December , and then release 0.4 :

# Features

- [x] Compatible with .Net 5
- [ ] More features for table (filters, fixed header/column)
- [ ] Add tree-select component
- [ ] Add image component
- [ ] Add resizable component

# Refactors

- [ ] Refactor form to support multi-field binding
- [x] Refactor select component
- [x] Merge i18n with date-picker locale

# Improvement

- [ ] Performance improvement
- [x] Fix known issues
- [ ] Add more tests

**Comment by 4nTrax** [comment]
Are there any updates when we can expect the 0.4 release?

**Comment by ElderJames** [comment]
Hi all! 

Just released 0.4.0.
We've done something outside of that milestone, and the task of that milestone will be implemented in the next release.

https://github.com/ant-design-blazor/ant-design-blazor/releases/tag/0.4.0

**Comment by 4nTrax** [comment]
So "outside of that milestone" means the 0.4 release does not support .NET 5?

If so:
Are there any updates when we can expect the 0.5 release, with .NET 5 support?

**Comment by ElderJames** [comment]
Hi @4nTrax ,

No, it's fully compatible with .NET 5. The documentation has been running on.net 5 RC for some time.
However, it is currently based on.net Core 3.1, and the new features in.NET 5 such as `JavaScript isolation`,`virtualization` are not yet in use.
