### ISSUE TITLE
MILESTONE: January 2021

### ISSUE THREAD

**Issue by ElderJames** [ant-design-blazor/ant-design-blazor#966]
Here are the milestones we plan to accomplish by January, and then release 0.6 :

# Features

- [ ] More features for table 
    - [x] multiple sorters
    - [ ] summary
- [ ] Add tree-select component

# Refactors

- [x] refactor the overlay with unbound way. #898 
- [x] table support `data index` binding like react version.

# Improvement

- [ ] Performance improvement
- [ ] Fix known issues
- [ ] Add more tests

We still welcome contributions. If someone wants to contribute, they just feel free to comment here and submit PRs.
