### ISSUE TITLE
MILESTONE: February 2021

### ISSUE THREAD

**Issue by ElderJames** [ant-design-blazor/ant-design-blazor#967]
Here are the milestones we plan to accomplish by February, and then release 0.7 :

# Features

- [ ] More features for table 
    - [ ] filters 
- [x] Add image component

# Refactors

- [ ] Refactor form to support multi-field binding

# Improvement

- [ ] Performance improvement
- [ ] Fix known issues
- [ ] Add more tests

We still welcome contributions. If someone wants to contribute, they just feel free to comment here and submit PRs.

**Comment by davidallenby** [comment]
Hi @ElderJames, thanks for your efforts on this library. I'm considering using AntBlazor in an enterprise project. However, one of our requirements is Table Filters. Do you think this release will happen in the next few months?

**Comment by ElderJames** [comment]
Hi @davidallenby , the table filters is working in progress. You will see the basic version tonight.
